print("-------------------CHALLENGE 2----------------------------")
day=int(input("Day = \n"))
month=input("Month = \n")
year = int(input("Year = \n"))
print(f'You were born in day {day} of {month} of {year}. Correct?')