something = input("Type something : \n")
print("Is {} numeric? \n".format(something),something.isnumeric())
print("Is {} alfa numeric? \n".format(something), something.isalnum())
print("Is {} uppercase ? \n".format(something), something.isupper())
print("Is {} lower ? \n".format(something), something.islower())
print("Is {} float ? \n".format(something), something.isdecimal())
print("Is {} ASCII code ?\n".format(something), something.isascii())
print("Is {} space? \n".format(something), something.isspace())
print("Is {} a title ?\n". format(something), something.istitle())
print("Is {} printable ? \n".format(something), something.isprintable())
